config/routes.rb
# coding: utf-8
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pronunciation/index'
  get 'pronunciation/only_word'
  get 'pronunciation/list_word'
  get 'pronunciation/store_alphabet_trainning'
  get 'admin/index'
  get 'admin/report'
  get 'build/index'
  resources :read_alouds, only: [:index, :chart, :report]
  get 'read_alouds/chart'
  get 'read_alouds/report'
  get 'course/create'
  post 'course/store'
  resources :course, only: [:edit, :update, :destroy]
  get 'home/course'
  resources :users, only: [:new, :create, :update]
  root "home#index"
  
  resources :sessions, only: [:new, :create, :destroy] 
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  resources :write_fr_dics, only: [:index, :public]
  resources :password_resets, only: [:edit, :update, :create, :new]

  get 'write_fr_dics/public'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Handle unavailable link
  get '*path' => redirect('/404_customize')

end

app/models/write_fr_dic.rb
class WriteFrDic < ApplicationRecord
end

app/controllers/write_fr_dics_controller.rb
class WriteFrDicsController < ApplicationController
  before_action :set_write_fr_dic, only: [:show, :edit, :update, :destroy]
  before_action :check_user
  
  # GET /write_fr_dics
  # GET /write_fr_dics.json
  # Pgae WFD in Course
  def index
    @write_fr_dics = WriteFrDic.all
    @count = params[:audio]
     
    if params[:status_id]
      @status_id = params[:status_id]
      wfd_status = Course.all.find_by_id(params[:status_id])
      wfd_status.update(:status => "In Progress")
    end
  end

  # Pgae WFD in Menu
  def public
    @write_fr_dics_result = WriteFrDic.select(:id, :result)
    @count = params[:audio]
  end

  # GET /write_fr_dics/1
  # GET /write_fr_dics/1.json
  def show
    
  end

  # GET /write_fr_dics/new
  def new
    @write_fr_dic = WriteFrDic.new
    
  end

  # GET /write_fr_dics/1/edit
  def edit
    
  end

  # POST /write_fr_dics
  # POST /write_fr_dics.json
  def create
    @write_fr_dic = WriteFrDic.new(write_fr_dic_params)
    
    respond_to do |format|
      if @write_fr_dic.save
        format.html { redirect_to @write_fr_dic, notice: 'Write fr dic was successfully created.' }
        format.json { render :show, status: :created, location: @write_fr_dic }
      else
        format.html { render :new }
        format.json { render json: @write_fr_dic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /write_fr_dics/1
  # PATCH/PUT /write_fr_dics/1.json
  def update
    respond_to do |format|
      if @write_fr_dic.update(write_fr_dic_params)
        format.html { redirect_to @write_fr_dic, notice: 'Write fr dic was successfully updated.' }
        format.json { render :show, status: :ok, location: @write_fr_dic }
      else
        format.html { render :edit }
        format.json { render json: @write_fr_dic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /write_fr_dics/1
  # DELETE /write_fr_dics/1.json
  def destroy
    @write_fr_dic.destroy
    respond_to do |format|
      format.html { redirect_to write_fr_dics_url, notice: 'Write fr dic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_write_fr_dic
      @write_fr_dic = WriteFrDic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def write_fr_dic_params
      params.require(:write_fr_dic).permit(:audio, :content)
    end
end

app/helpers/write_fr_dics_helper.rb
module WriteFrDicsHelper
  require 'fuzzystringmatch'

  def count_matching_rate(left, right)
    jarow = FuzzyStringMatch::JaroWinkler.create( :native )
    p jarow.getDistance(left, right)
  end
end

app/views/write_fr_dics/_form.html.erb
<%= form_with(model: write_fr_dic, local: true) do |form| %>
  <% if write_fr_dic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(write_fr_dic.errors.count, "error") %> prohibited this write_fr_dic from being saved:</h2>

      <ul>
      <% write_fr_dic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/write_fr_dics/_public.html.erb
<div class="container bg-white shadow p-2">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item"><a href="">Listening</a></li>
      <li class="breadcrumb-item active" aria-current="page">Write From Dictation</li>
    </ol>
  </nav>
  <div id="placement" class="text-center"><h1 class="clock countDown"></h1></div>
  <div class="panel panel-default">
    
    <!--form-content-->
    <form id="form-id">
      <!--Progressbar-->
      <% k = 0 %>
      <div id="ng-app" ng-app="diffDemo" layout="column" flex ng-controller="diffCtrl">
        <% WriteFrDic.all.each do |sens| %>

        <fieldset class="writeFromDitation">
          <h2 class='title'>Sentence <%= k = k + 1 %> </h2>
          <h3 class='sub-title'>
            <div class="page-header">
	            <span class="minutes">This audio will auto play after </span><span class="timer">05</span><span>s</span>
            </div>
          </h3>
          
          <div class="page-header">
            <%= audio_tag "#{sens.audio}", controls: true, id:"timer-beep", class: "timer-beep" %>
          </div>
          <div class="md-form" data-ng-init="anyFunction()">
            <textarea layout-fill id="sens-content<%= k - 1%>" class="md-textarea left form-control" placeholder="Enter word is here after you heard ..."></textarea>
            <h1 layout-fill id="sens-content-right" class="md-textarea right form-control" style="display: none;"><%= sens.result%></h1>
            
            <!-- Modal result-->
            <div class="modal fade" id="myModal<%= k %>" role="dialog" >
              <div class="modal-dialog" role="document">
                <!-- Modal result-->
                <div class="modal-content" >
                  <div class="modal-header" style="background-color:wheat;">
                    <h5 class="modal-title" id="exampleModalLabel">CONGRATULATE</h5>
                  </div>
                  <div class="modal-body" style="padding:40px 50px;">
                    THIS IS YOUR RESULT
                    <form role="form">
                      <div class="form-group" >
                        <ol >
                          <li ng-repeat="x in products"><pre class="textdiff" processing-diff left-obj="x.left" right-obj="x.right" options="options"></pre></li>
                          
                        </ol>
                      </div>                        
                    </form>
                  </div>
                  <div class="modal-footer" style="justify-content: space-between;">
                    <button type="button" class="btn btn-danger pull-left" data-dismiss="modal" ng-click="clear()" onclick="location.reload()"><span class="fa fa-rotate-left"></span></button>
                    <%= link_to '<span class="fa fa-align-justify"></span>'.html_safe, home_course_path,  class: "btn btn-default pull-left", style: "color:white;"%>
                  </div>
                </div>
              </div>
            </div>              
          </div>
          <!-- Modl result -->
          
          <% if (k == @count.to_i) %>
          <input type='button' value='Finish' ng-click="result()" class="custom-button finish" onclick="$('#myModal<%= k %>').modal({backdrop: 'static', keyboard: false})">
          <% else %>
          <input type='button' name='next' class='next-button custom-button' value="Next">
          <% end %>
        </fieldset>
        <% end %>
    </form>
    <!-- end form -->
    </div>
  </div>
</div>
</div>

<!-- Model errors -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:red;">
        <h5 class="modal-title" id="exampleModalLongTitle">TIMEOUT</h5>
      </div>
      <div class="modal-body">
        You didn't finished this test!!!
        Please chosse do this again or back to course
      </div>
      <div class="modal-footer" style="justify-content: space-between;">
        <button type="button" class="btn btn-primary pull-left" data-dismiss="modal" ng-click="clear()" onclick="location.reload()"><span class="fa fa-rotate-left"></span></button>
        <%= link_to '<span class="fa fa-align-justify"></span>'.html_safe, home_course_path,  class: "btn btn-secondary pull-left", style: "color:white;"%>
      </div>
    </div>
  </div>
</div>
<!-- Model errors -->

<script>
  
  $(document).on('turbolinks:load', function() {
    // Reload page once to fix errors don't show angular-diff-math-path 
      if(document.URL.indexOf("#")==-1){
          // Set the URL to whatever it was plus "#loaded".
          url = document.URL+"#loaded";
          location = "#loaded";
          //Reload the page using reload() method
          location.reload(true);
      };

    // count time to do test
    var interval1, count, min, sec;
    count = $('fieldset').length * 30;
    min = Math.floor(count/60)
    sec = Math.floor(count%60)
    
    // $('.clock').text(min.toString()+':'+sec.toString());
    $('.clock').text('00 : 30');
    countdown();

    function countdown() {
      clearInterval(interval1);
      
      interval1 = setInterval( function() {
        var timer = $('.clock').html();
        timer = timer.split(':');
        var minutes = timer[0];
        var seconds = timer[1];
        seconds -= 1;
        if (minutes < 0) return;
        else if (seconds < 0 && minutes != 0) {
          minutes -= 1;
          seconds = 59;
        }
        else if (seconds < 10 && length.seconds != 2) seconds = '0' + seconds;

        $('.clock').html(minutes + ':' + seconds);

        if (minutes == 0 && seconds == 0)
        {
          $('#exampleModalCenter').modal({backdrop: 'static', keyboard: false});
          clearInterval(interval1);
        };
      }, 1000);
      
    };
    // --------------------
    // open result when time out
    $('.finish').click(function() {
      clearInterval(interval1);
    });
    // ------------------------
    // count time to play audio
      
    var Pause, interval, settime, timer, total_time;
    timer = 5;
    interval = setInterval((function() {
      timer--;
      $('.timer').text(timer);
      if (timer === 0) {
        Pause();
        document.getElementById('timer-beep').play();
        clearInterval(interval);
      }
    }), 1000);
    $('.next-button').prop('disabled', true);
    $('.prev-button').prop('disabled', true);
    setTimeout((function() {
      $('.next-button').prop('disabled', false);
      $('.prev-button').prop('disabled', false);
    }), 10000);
    // -----------------------------
    Pause = function() {
      $('.timer-beep').each(function(i) {
        $(this).get($('fieldset').index(i)).pause();
        $(this).get($('fieldset').index(i)).currentTime = 0;
      });
    };
    // Analyze click next, previous, finish button
    $('.next-button').click(function() {
      var current, next;
      current = $(this).parent();
      next = $(this).parent().next();
      Pause();
      current.hide();
      next.show();
      $('.next-button').prop('disabled', true);
      $('.prev-button').prop('disabled', true);
      $('.finish').prop('disabled', true);
      setTimeout((function() {
        $('.next-button').prop('disabled', false);
        $('.prev-button').prop('disabled', false);
        $('.finish').prop('disabled', false);
      }), 10000);
      timer = 5;
      interval = setInterval((function() {
        timer--;
        $('.timer').text(timer);
        if (timer === 0) {
          Pause();
          $('.timer-beep').get($('fieldset').index(next)).play();
          clearInterval(interval);
        }
      }), 1000);
    });
  });

</script>
<script>
  
  var app = angular.module('diffDemo', ['ngMaterial', 'diff-match-patch']);
  app.config(function($mdThemingProvider) {
    $mdThemingProvider.theme('default')
      .primaryPalette('indigo')
      .accentPalette('blue');
  });
  
  app.controller('diffCtrl', ['$scope', function($scope) {
    
    $scope.anyFunction = function(){
      
      $scope.left = "";
      $scope.right = "";
      
      $scope.options = {
        editCost: 4,
        interLineDiff: true,
        ignoreTrailingNewLines: true,
        attrs: {
          insert: {
            'data-attr': 'insert',
            'class': 'insertion'
          },
          delete: {
            'data-attr': 'delete'
          },
          equal: {
            'data-attr': 'equal'
          }
        }
      };
      
    };
    
    $scope.clear = function() {
      $scope.products = [];
       $('fieldset').each(function(i) {
         document.getElementById('sens-content'+ i).value = ""
      });
    };

    $scope.result = function() {
      $scope.products = [];
      $('fieldset').each(function(i) {
        $scope.addMe1 = document.getElementById('sens-content'+ i).value;
        
        $scope.addMe2 = $('.right')[i].innerText;

        $scope.products.push({"left":$scope.addMe1, "right":$scope.addMe2});
        
      });
      
    };
    
  }]);


</script>

app/views/write_fr_dics/_test.html.erb
<div class="container bg-white shadow p-2">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item"><a href="/home/course">Course</a></li>
      <li class="breadcrumb-item"><a href="">Schedule</a></li>
      <li class="breadcrumb-item active" aria-current="page">Write From Dictation</li>
    </ol>
  </nav>
  <div id="placement" class="text-center"><h1 class="clock countDown"></h1></div>
  <div class="panel panel-default">
    
    <!--form-content-->
    <form id="form-id">
      <!--Progressbar-->
      <% k = 0 %>
      <!-- Progress bar sentence -->
      <!-- <ul class='progress' style="height: 1.3rem;"> -->
        <!--   <li class="active"></li> -->
        <!--   <% (2..@count.to_i). each do |sentence| %> -->
        <!--   <li><% sentence %></li> -->
        <!--   <% end %> -->
        <!-- </ul> -->
      <div id="ng-app" ng-app="diffDemo" layout="column" flex ng-controller="diffCtrl">
        <% WriteFrDic.all.sample(@count.to_i).each do |sens| %>

        <fieldset>
          <h2 class='title'>Sentence <%= k = k + 1 %> / <%= @count %> </h2>
          <h3 class='sub-title'>
            <div class="page-header">
	            <span class="minutes">This audio will auto play after </span><span class="timer">05</span><span>s</span>
            </div>
          </h3>
          
          <div class="page-header">
            <%= audio_tag "#{sens.audio}", controls: true, id:"timer-beep", class: "timer-beep" %>
          </div>
          <div class="md-form" data-ng-init="anyFunction()">
            <textarea layout-fill id="sens-content<%= k - 1%>" class="md-textarea left form-control" placeholder="Enter word is here after you heard ..."></textarea>
            <h1 layout-fill id="sens-content-right" class="md-textarea right form-control" style="display: none;"><%= sens.result%></h1>
            
            <!-- Modal result-->
            <div class="modal fade" id="myModal<%= k %>" role="dialog" >
              <div class="modal-dialog" role="document">
                <!-- Modal result-->
                <div class="modal-content" >
                  <div class="modal-header" style="background-color:wheat;">
                    <h5 class="modal-title" id="exampleModalLabel">CONGRATULATE</h5>
                  </div>
                  <div class="modal-body" style="padding:40px 50px;">
                    THIS IS YOUR RESULT
                    <form role="form">
                      <div class="form-group" >
                        <ol >
                          <li ng-repeat="x in products"><pre class="textdiff" processing-diff left-obj="x.left" right-obj="x.right" options="options"></pre></li>
                          
                        </ol>
                      </div>                        
                    </form>
                  </div>
                  <div class="modal-footer" style="justify-content: space-between;">
                    <button type="button" class="btn btn-danger pull-left" data-dismiss="modal" ng-click="clear()" onclick="location.reload()"><span class="fa fa-rotate-left"></span></button>
                    <%= link_to '<span class="fa fa-align-justify"></span>'.html_safe, home_course_path,  class: "btn btn-default pull-left", style: "color:white;"%>
                  </div>
                </div>
              </div>
            </div>              
          </div>
          <!-- Modl result -->
          
          <% if (k == @count.to_i) %>
          <input type='button' value='Finish' ng-click="result()" class="custom-button finish" onclick="$('#myModal<%= k %>').modal({backdrop: 'static', keyboard: false})">
          <% else %>
          <input type='button' name='next' class='next-button custom-button' value="Next">
          <% end %>
        </fieldset>
        <% end %>
    </form>
    <!-- end form -->
    </div>
  </div>
</div>
</div>

<!-- Model errors -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:red;">
        <h5 class="modal-title" id="exampleModalLongTitle">TIMEOUT</h5>
      </div>
      <div class="modal-body">
        You didn't finished this test!!!
        Please chosse do this again or back to course
      </div>
      <div class="modal-footer" style="justify-content: space-between;">
        <button type="button" class="btn btn-primary pull-left" data-dismiss="modal" ng-click="clear()" onclick="location.reload()"><span class="fa fa-rotate-left"></span></button>
        <%= link_to '<span class="fa fa-align-justify"></span>'.html_safe, home_course_path,  class: "btn btn-secondary pull-left", style: "color:white;"%>
      </div>
    </div>
  </div>
</div>
<!-- Model errors -->

<script>
  
  $(document).on('turbolinks:load', function() {
    // Reload page once to fix errors don't show angular-diff-math-path 
      if(document.URL.indexOf("#")==-1){
          // Set the URL to whatever it was plus "#loaded".
          url = document.URL+"#loaded";
          location = "#loaded";
          //Reload the page using reload() method
          location.reload(true);
      };

    // count time to do test
    var interval1, count, min, sec;
    count = $('fieldset').length * 30;
    min = Math.floor(count/60)
    sec = Math.floor(count%60)
    
    $('.clock').text(min.toString()+':'+sec.toString());
    countdown();

    function countdown() {
      clearInterval(interval1);
      
      interval1 = setInterval( function() {
        var timer = $('.clock').html();
        timer = timer.split(':');
        var minutes = timer[0];
        var seconds = timer[1];
        seconds -= 1;
        if (minutes < 0) return;
        else if (seconds < 0 && minutes != 0) {
          minutes -= 1;
          seconds = 59;
        }
        else if (seconds < 10 && length.seconds != 2) seconds = '0' + seconds;

        $('.clock').html(minutes + ':' + seconds);

        if (minutes == 0 && seconds == 0)
        {
          $('#exampleModalCenter').modal({backdrop: 'static', keyboard: false});
          clearInterval(interval1);
        };
      }, 1000);
      
    };
    // --------------------
    // open result when time out
    $('.finish').click(function() {
      clearInterval(interval1);
    });
    // ------------------------
    // count time to play audio
      
    var Pause, interval, settime, timer, total_time;
    timer = 5;
    interval = setInterval((function() {
      timer--;
      $('.timer').text(timer);
      if (timer === 0) {
        Pause();
        document.getElementById('timer-beep').play();
        clearInterval(interval);
      }
    }), 1000);
    $('.next-button').prop('disabled', true);
    $('.prev-button').prop('disabled', true);
    setTimeout((function() {
      $('.next-button').prop('disabled', false);
      $('.prev-button').prop('disabled', false);
    }), 10000);
    // -----------------------------
    Pause = function() {
      $('.timer-beep').each(function(i) {
        $(this).get($('fieldset').index(i)).pause();
        $(this).get($('fieldset').index(i)).currentTime = 0;
      });
    };
    // Analyze click next, previous, finish button
    $('.next-button').click(function() {
      var current, next;
      current = $(this).parent();
      next = $(this).parent().next();
      Pause();
      current.hide();
      next.show();
      $('.next-button').prop('disabled', true);
      $('.prev-button').prop('disabled', true);
      $('.finish').prop('disabled', true);
      setTimeout((function() {
        $('.next-button').prop('disabled', false);
        $('.prev-button').prop('disabled', false);
        $('.finish').prop('disabled', false);
      }), 10000);
      timer = 5;
      interval = setInterval((function() {
        timer--;
        $('.timer').text(timer);
        if (timer === 0) {
          Pause();
          $('.timer-beep').get($('fieldset').index(next)).play();
          clearInterval(interval);
        }
      }), 1000);
    });
  });

</script>
<script>
  
  var app = angular.module('diffDemo', ['ngMaterial', 'diff-match-patch']);
  app.config(function($mdThemingProvider) {
    $mdThemingProvider.theme('default')
      .primaryPalette('indigo')
      .accentPalette('blue');
  });
  
  app.controller('diffCtrl', ['$scope', function($scope) {
    
    $scope.anyFunction = function(){
      
      $scope.left = "";
      $scope.right = "";
      
      $scope.options = {
        editCost: 4,
        interLineDiff: true,
        ignoreTrailingNewLines: true,
        attrs: {
          insert: {
            'data-attr': 'insert',
            'class': 'insertion'
          },
          delete: {
            'data-attr': 'delete'
          },
          equal: {
            'data-attr': 'equal'
          }
        }
      };
      
    };
    
    $scope.clear = function() {
      $scope.products = [];
       $('fieldset').each(function(i) {
         document.getElementById('sens-content'+ i).value = ""
      });
    };

    $scope.result = function() {
      $scope.products = [];
      $('fieldset').each(function(i) {
        $scope.addMe1 = document.getElementById('sens-content'+ i).value;
        
        $scope.addMe2 = $('.right')[i].innerText;

        $scope.products.push({"left":$scope.addMe1, "right":$scope.addMe2});
        
      });
      
    };
    
  }]);

</script>

app/views/write_fr_dics/edit.html.erb
<h1>Editing Write Fr Dic</h1>

<%= render 'form', write_fr_dic: @write_fr_dic %>

<%= link_to 'Show', @write_fr_dic %> |
<%= link_to 'Back', write_fr_dics_path %>

app/views/write_fr_dics/new.html.erb
<h1>New Write Fr Dic</h1>

<%= render 'form', write_fr_dic: @write_fr_dic %>

<%= link_to 'Back', write_fr_dics_path %>

app/views/write_fr_dics/public.html.erb
<script src='/assets/write_fr_dic.js' type="text/javascript"></script>
<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src='//code.responsivevoice.org/responsivevoice.js'></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<%= render partial: 'home/header' %>

<div class="row justify-content-center">
    <div class="col-lg-10">
        <% k = 1 %>
        <div class="read-alouds bg-white shadow p-2">
            <div id="placement" class="text-center d-none"><h1 class="clock countDown"></h1></div>
            <h6 class="font-weight-bold mb-4">Type what you hear in the box below exactly as you hear it. You can replay as many times as you want by click icon <span><%=image_tag("listen.jpg", size: "40x40")%></span>.</h6>
            <% @write_fr_dics_result.sample(WriteFrDic.all.size).each do |sens| %>
                <div class="row justify-content-center">
                    <div class="col-10" id="data-<%= k %>" style="display: none;">
                        <div class="text-center">
                            <h2 class="text-blue-en4all sentence">SENTENCE <%= k %></h2>
                            <h3 class='sub-title'>
                                <div class="page-header">
                                        <span class="minutes text-danger">This audio will auto play after </span><span class="timer text-danger">05</span><span class="text-danger">s</span>
                                </div>
                            </h3>
                            
                            <div class="page-header">
                                <p class="d-none" id="content<%= k %>"><%= sens.result%></p>
                                <span><%=image_tag("listen.jpg", size: "100x70", :class => "audio_play") %></span>
                            </div>
                        </div>
                        <div class="md-form">
                            <textarea layout-fill id="sens-content<%= k %>" class="left form-control p-4" rows="4"></textarea>
                            <h1 layout-fill id="sens-content-right" class="md-textarea right form-control" style="display: none;"><%= sens.result%></h1>            
                        </div>
                        <div class="d-none" id="result-<%= k %>">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div style="width: 250px;">
                                        <div class="percent">
                                            <h5 id="percent-<%= k %>"></h5>
                                        </div>
                                        <canvas id="accuracy-<%= k %>"></canvas>
                                    </div>
                                </div>
                                <div class="col-sm-8">
                                    <h3 class="font-weight-bold text-success" id="suggest-<%= k %>">Good</h3>
                                    <h6 class="text-blue-en4all font-italic" id="suggestDetail-<%= k %>"></h6>
                                    <div class="d-none" id="output-<%= k %>"></div>
                                    <div class="d-none" id="accuracy-<%= k %>"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <% k = k + 1%>
            <% end %>
        </div>
        </div>
    </div>
</div>
<div class="action-bottom" style="left: 0">
    <div class="float-right">
        <button id="retry-button" class='edit btn bg-blue-en4all text-light d-none'>Retry</button>
        <button id="next-button" class='edit btn bg-blue-en4all text-light d-none'>Next</button>
        <button id="verify-result" class="edit btn bg-blue-en4all text-light mr-2" disabled="true">Verify</button>
    </div>
</div>
<script>  
  speechSynthesis.cancel();  
</script>

app/views/write_fr_dics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_write_fr_dic_path(@write_fr_dic) %> |
<%= link_to 'Back', write_fr_dics_path %>