config/routes.rb
# coding: utf-8
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pronunciation/index'
  get 'pronunciation/only_word'
  get 'pronunciation/list_word'
  get 'pronunciation/store_alphabet_trainning'
  get 'admin/index'
  get 'admin/report'
  get 'build/index'
  resources :read_alouds, only: [:index, :chart, :report]
  get 'read_alouds/chart'
  get 'read_alouds/report'
  get 'course/create'
  post 'course/store'
  resources :course, only: [:edit, :update, :destroy]
  get 'home/course'
  resources :users, only: [:new, :create, :update]
  root "home#index"
  
  resources :sessions, only: [:new, :create, :destroy] 
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  resources :write_fr_dics, only: [:index, :public]
  resources :password_resets, only: [:edit, :update, :create, :new]

  get 'write_fr_dics/public'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Handle unavailable link
  get '*path' => redirect('/404_customize')

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.first.downcase + email[1..-1] }
  before_create { generate_token(:auth_token) }

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver_now
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  #  PASSWORD_VALIDATOR = /(      # Start of group
  #         (?:                        # Start of nonmatching group, 4 possible solutions
  #           (?=.*[a-z])              # Must contain one lowercase character
  #           (?=.*[A-Z])              # Must contain one uppercase character
  #           (?=.*\W)                 # Must contain one non-word character or symbol
  #         |                          # or...
  #           (?=.*\d)                 # Must contain one digit from 0-9
  #           (?=.*[A-Z])              # Must contain one uppercase character
  #           (?=.*\W)                 # Must contain one non-word character or symbol
  #         |                          # or...
  #           (?=.*\d)                 # Must contain one digit from 0-9
  #           (?=.*[a-z])              # Must contain one lowercase character
  #           (?=.*\W)                 # Must contain one non-word character or symbol
  #         |                          # or...
  #           (?=.*\d)                 # Must contain one digit from 0-9
  #           (?=.*[a-z])              # Must contain one lowercase character
  #           (?=.*[A-Z])              # Must contain one uppercase character
  #         )                          # End of nonmatching group with possible solutions
  #         .*                         # Match anything with previous condition checking
  # )/x 
  #   validates :password_confirmation, :password, :email, presence: true
  #   validates :email, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
  #   validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  
  #   validates :password, {confirmation: true, length: { minimum: 8 }, format: {
  #                           with: PASSWORD_VALIDATOR,
  #                           message: "must contain 3 of the following 4: a lowercase letter, an uppercase letter, a digit, a non-word character or symbol"
  #                         }}
  validates :password, confirmation: true
  has_secure_password
  has_many :courses, dependent: :destroy
  has_many :read_aloud_charts, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    begin
      if @user.save
        flash[:success] = "Welcome #{@user.email} to the web EN4PR! Please login to learn English "
        redirect_to login_path
      else
        flash[:danger] = " Errors in sign up. Please sign up again."
        redirect_to signup_path
      end
    rescue ActiveRecord::RecordNotUnique
      flash[:danger] = " #Your acoount #{@user.email} have used. Please use it to login."
      redirect_to login_path
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script src='/assets/recaptcha.js' type="text/javascript"></script>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<div class="container signupPage p-4">
  <!-- Icon -->
  
  <!-- Tabs Titles -->

  <!-- Icon -->
  <div class="text-center">
    <img src="https://img.icons8.com/clouds/100/000000/lock.png">
  </div>
  <!-- Sign up Form -->
  <%= form_with(model: user, local: true) do |form| %>
  <div class="row mb-2">
    <div class="col-12 col-lg-4">
      <label class="text-lg-right">Email: <span class="text-danger">*</span></label>
                                                                    </div>
    <%= form.email_field :email, required: true, class: "fadeIn second col-12 col-lg-4",  id: "login", placeholder: "Email" %>
  </div>
  <div class="row mb-2">
    <div class="col-12 col-lg-4">
      <label class="text-lg-right">Password: <span class="text-danger">*</span></label>
                                                                       </div>
    <%= form.password_field :password, required: true, id: "password", class: "fadeIn third col-12 col-lg-4", placeholder: "Password", pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*_=+-]).{8,}$", title: "Must contain at least one number, one uppercase, one lowercase and one special letter, and at least 8 or more characters", onchange: "this.setCustomValidity(this.validity.patternMismatch ? 'Must contain at least one number, one uppercase, one lowercase and one special letter, and at least 8 or more characters' : ''); if(this.checkValidity()) form.password_confirmation.pattern = this.value;" %>
  </div>
  <div class="row mb-2">
    <div class="col-12 col-lg-4">
      <label class="text-lg-right">Password Confirm: <span class="text-danger">*</span></label>                                                                              </div>
                                                                                                                                                                          <%= form.password_field :password_confirmation, required: true, id: "password_confirmation", class: "fadeIn third col-12 col-lg-4", placeholder: "Password Confirmation", pattern: "(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}", onchange: "this.setCustomValidity(this.validity.patternMismatch ? 'Please enter the same Password' : '');" %>
  </div>
  <div 
      class="g-recaptcha mb-4 mt-4 text-center" 
      data-callback="reCaptchaCallback"
    >
    </div>
  <div class="mt-2 mb-2 text-center">
    <%= form.submit 'Sign Up', class: 'btn bg-blue-en4all text-light', id: "btnSigup", disabled: true %>
    <%= link_to 'CANCEL', logout_path, :class => "btn btn-secondary text-light" %>
  </div>
  <% end %>
</div>

<script>
  function reCaptchaCallback() {
    $("#btnSigup").attr("disabled", false);
  }
  $('.sub-menu-parent').hide();
</script>

app/views/users/edit.html.erb
<%= render 'home/header'%>
<div class="w-100">
    <h4 class="text-center mb-4">Editting User</h4>
    <%= render 'form', user: @user %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="wrapper fadeInDown">
  <%= render 'form', user: @user %>
<div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>