config/routes.rb
# coding: utf-8
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pronunciation/index'
  get 'pronunciation/only_word'
  get 'pronunciation/list_word'
  get 'pronunciation/store_alphabet_trainning'
  get 'admin/index'
  get 'admin/report'
  get 'build/index'
  resources :read_alouds, only: [:index, :chart, :report]
  get 'read_alouds/chart'
  get 'read_alouds/report'
  get 'course/create'
  post 'course/store'
  resources :course, only: [:edit, :update, :destroy]
  get 'home/course'
  resources :users, only: [:new, :create, :update]
  root "home#index"
  
  resources :sessions, only: [:new, :create, :destroy] 
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  resources :write_fr_dics, only: [:index, :public]
  resources :password_resets, only: [:edit, :update, :create, :new]

  get 'write_fr_dics/public'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Handle unavailable link
  get '*path' => redirect('/404_customize')

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/ipa.rb
class Ipa < ApplicationRecord
  serialize :list_words
  serialize :description
end

app/models/ipa_user.rb
class IpaUser < ApplicationRecord
  serialize :alphabet_wrong
  serialize :alphabet_done
  serialize :alphabet_trainning
end

app/models/read_aloud.rb
class ReadAloud < ApplicationRecord
end

app/models/read_aloud_chart.rb
class ReadAloudChart < ApplicationRecord
  validates :rate, presence: true
  belongs_to :users, optional: true
end

app/models/read_aloud_report.rb
class ReadAloudReport < ApplicationRecord
end

app/models/unknow_ipa.rb
class UnknowIpa < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.first.downcase + email[1..-1] }
  before_create { generate_token(:auth_token) }

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver_now
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  #  PASSWORD_VALIDATOR = /(      # Start of group
  #         (?:                        # Start of nonmatching group, 4 possible solutions
  #           (?=.*[a-z])              # Must contain one lowercase character
  #           (?=.*[A-Z])              # Must contain one uppercase character
  #           (?=.*\W)                 # Must contain one non-word character or symbol
  #         |                          # or...
  #           (?=.*\d)                 # Must contain one digit from 0-9
  #           (?=.*[A-Z])              # Must contain one uppercase character
  #           (?=.*\W)                 # Must contain one non-word character or symbol
  #         |                          # or...
  #           (?=.*\d)                 # Must contain one digit from 0-9
  #           (?=.*[a-z])              # Must contain one lowercase character
  #           (?=.*\W)                 # Must contain one non-word character or symbol
  #         |                          # or...
  #           (?=.*\d)                 # Must contain one digit from 0-9
  #           (?=.*[a-z])              # Must contain one lowercase character
  #           (?=.*[A-Z])              # Must contain one uppercase character
  #         )                          # End of nonmatching group with possible solutions
  #         .*                         # Match anything with previous condition checking
  # )/x 
  #   validates :password_confirmation, :password, :email, presence: true
  #   validates :email, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
  #   validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  
  #   validates :password, {confirmation: true, length: { minimum: 8 }, format: {
  #                           with: PASSWORD_VALIDATOR,
  #                           message: "must contain 3 of the following 4: a lowercase letter, an uppercase letter, a digit, a non-word character or symbol"
  #                         }}
  validates :password, confirmation: true
  has_secure_password
  has_many :courses, dependent: :destroy
  has_many :read_aloud_charts, dependent: :destroy
end

app/models/write_fr_dic.rb
class WriteFrDic < ApplicationRecord
end

app/models/wrong_pronunciation.rb
class WrongPronunciation < ApplicationRecord
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_user
  
  def index
    if current_user.email == "admin@en4pr.com"
      redirect_to  admin_index_path
    end
    
  end

  def course
    if params[:status_id]
      status = Course.all.find_by_id(params[:status_id])
      status.update(:status => "Done")
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def list_7_days(user_id)
    list = ReadAloudReport.where("date(updated_at) between :start and :end", {start: 7.days.ago.to_date, end: Date.today}).where(:user_id => user_id).order(:updated_at)
    length_list = list.count
    array = []
    if list != []
      days = list.first.updated_at.to_date
      
      (0..6).each do |x|
        
        array = array + [["#{days + x.day}"] + list.select{|m| m.updated_at.to_date == days + x.day}.map{|k| k.percent}]
      end
    end
    # data = [['Year', 'Sales', 'Expenses', 'Profit'],
    #         ['2014', 100, 40, 20],
    #         ['2015', 11, 46, 25],
    #         ['2016', 60, 11, 30],
    #         ['2017', 10, 54, 35,10,56,90,80]]
    data = [['DATES']] + array

    return @data = (1..10).map do |i|
      {
        name: data.first[i],
        data: data[1..-1].map { |x| [ x[0], x[i] ] }
      }
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/build_helper.rb
module BuildHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ipa_english_helper.rb
module IpaEnglishHelper
  require "sqlite3"
  require "humanize"
  def to_ipa(words)
    words = to_exactly_type(words)
    db = SQLite3::Database.new 'ipagem.db'

    new_word = words.map do |w|
      w = w.split(/\W+/).join(' ')
      
      temp = db.execute("SELECT phonetic FROM phonetics WHERE word == '#{w.upcase}'")
      temp.join(' ').to_s
      
    end
    p new_word*" "

  end

  
  def is_number(x)
    Float(x) != nil rescue false
  end

  def to_exactly_type(words)

    words = words.split.map do |w|
      # Remove . and , at end string 
      w = w.sub(/\.+$/, '').sub(/\,+$/, '') 
      if is_number(w)
        w = w.to_f.humanize
        check_pharse(w)
      else
        w
      end
    end
    return words.to_sentence.split(' ')
  end

  # Remove - when convert humanize of number
  def check_pharse(text)
    if text.split.count > 1
      text = text.gsub("-", " ")
    end
    return text
  end
  
  
end

app/helpers/read_alouds_helper.rb
module ReadAloudsHelper
  
  def get_chart_user()
    ReadAloudChart.where(user_id:current_user.id).order(:updated_at)
  end
  def list_days()
    data = get_chart_user()
    days = data.pluck(:updated_at).map{|x| Date.parse(x.to_s).to_s}.uniq
  end

  # def rate_by_day()
  def get_list_rate()
    data = get_chart_user()
    rates =  data.pluck(:rate)
    if rates.count < 30

      rates = rates + [0] * (30 - rates.count)
    else
      rates.last(30)
    end
  end

  def get_list_sentence()
    
    data = get_chart_user()
    
    sents =  data.pluck(:sentence).map{|x| "Sentence " + x.to_s}
    if sents.count < 30
      sents = sents + ["No data"] * (30 - sents.count)
    else
      sents.last(30)
    end
  end
  
end
# JSON.parse(list_days.replace(/&quot;/g,'"')),

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_create_form_course.html.erb
<%= form_with url: course_store_path, class: 'panel-body post-form' do |f| %>
    <div class="row d-flex" style="border-top-style: double;padding-top: 15px; font-family: 'Roboto', sans-serif; font-size: 15px;">
        <div class="col-1 col-course-day">
            <div class="md-form" style="margin-top: unset">
                <input class="form-control" id="input-char-counter" type="number" min="1" step="1" name="day_id" placeholder="1" required>
          </div>
        </div>
        <div class="col-4 col-course-skill">
          <!-- <% grouped_options_skill = [['Speaking', ['Read Aloud','Repeat Sentence','Describe Image', 'Retell Lecture', 'Answer Short Question']],['Writing', ['Summarise Written Text','Essay']], ['Reading', ['Reading & Writing Fill In Blanks','Multiple Choice, Multiple Answer','Re-order Paragraph', 'Fill In Blanks (Drag & Drop)', 'Multiple Choice, Single Answer']], ['Listening', ['Summarize Spoken Text', 'Multiple Choice, Multiple Answer', 'Fill In Blanks', 'Highlight Correct Summary', 'Multiple Choice, Single Answer', 'Select Missing Word', 'Highlight Incorrect Words', 'Write From Dictation']]] %> -->
          <% grouped_options_skill = [['Speaking', ['Read Aloud']], ['Listening', ['Write From Dictation']]] %>
          <%= f.select :skill, grouped_options_for_select(grouped_options_skill), {},{class: "course-select form-control input-sm"}%>
        </div>
        <div class="col-2 col-course-quality">
            <%= f.number_field :quality, min: 1, class: "grade-select form-control input-sm", required: true, placeholder: "1"%>
        </div>
        <!-- <div class="col-6 col-md-2"> -->
        <!--     <% grouped_options_status = ['Not Starting', 'In Progress', 'Done'] %> -->
        <!--     <%= f.select :status, options_for_select(grouped_options_status, 'Not Starting'), {}, {class: "credits-select form-control input-sm"} %> -->
        <!-- </div> -->
        <div class="col-2 col-course-status"></div>
        <div class="col-3 col-course-action">
            <button type="submit" name="commit" class="test btn-sm btn-success"><span class="fa fa-plus"></span></button>
        </div>
    </div>
<% end %>

app/views/home/_edit_form_course.html.erb
<%= form_for(course, :html => {:class => 'panel-body', :style => 'display:none;' }) do |f| %>
    <div class="row d-flex mb-2">
        <div class="col-1 col-course-day"></div>
        <div class="col-4 col-course-skill">
            <% grouped_options_skill = [['Speaking', ['Read Aloud','Repeat Sentence','Describe Image', 'Retell Lecture', 'Answer Short Question']],['Writing', ['Summarise Written Text','Essay']], ['Reading', ['Reading & Writing Fill In Blanks','Multiple Choice, Multiple Answer','Re-order Paragraph', 'Fill In Blanks (Drag & Drop)', 'Multiple Choice, Single Answer']], ['Listening', ['Summarize Spoken Text', 'Multiple Choice, Multiple Answer', 'Fill In Blanks', 'Highlight Correct Summary', 'Multiple Choice, Single Answer', 'Select Missing Word', 'Highlight Incorrect Words', 'Write From Dictation']]] %>
            <%= f.select :skill, grouped_options_for_select(grouped_options_skill, selected: course.skill), {}, {class: "course-select form-control input-sm"}%>
        </div>
        <div class="col-2 col-course-quality">
            <% grouped_options_quality = ['5', '6','7','8', '9', '10', '11', '12','13', '14'] %>
            <%= f.select :quality, options_for_select(grouped_options_quality, selected: course.quality), {}, {class: "grade-select form-control input-sm"} %>
        </div>
        <!-- <div class="col-6 col-md-2"> -->
        <!--     <% grouped_options_status = ['Done', 'In Progress','Not Starting'] %> -->
        <!--     <%= f.select :status, options_for_select(grouped_options_status, selected: course.status), {}, {class: "credits-select form-control input-sm"}%> -->
        <!-- </div> -->
        <div class="col-2 col-course-status"></div>
        <div class="col-3 col-course-action">
            <button type="submit" class="save btn-sm btn-success"><span class="fa fa-floppy-o"></span></button>
        </div>
    </div>
<% end %>

app/views/home/_header.html.erb
<nav class="fixed-top bg-blue-en4all shadow">
  <div class="row" id="small-sidebar">
    <div class="col-2 pl-4 pt-2 pb-2" id="act-toggle-sidebar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span> 
    </div>

    <div class="col-8 text-center p-1">
      <%=image_tag("favicon.ico", size: "42x42") %>
    </div>
  </div>

  <div id="user-info">
    <ul >
      <li id="act-user-info" class="avatar d-flex float-right sub-menu-parent">
        <%=image_tag("cuteCat.jpg") %>
      </li>
    </ul> 
  </div>
  
  <div class="d-none" id="content-user-info"> 
    <ul>
      <li class="sub-menu-parent"><a data-turbolinks='false' class="menu" href="<%= logout_path %>"><h2 class="menu-title">Log out</h2></a></li>
    </ul>
  </div>
  

    <ul class="hList" id="content-sidebar" style="list-style: none;">

      <li class="sub-menu-parent">
        <a data-turbolinks='false' href="/" class="menu" id="home"><h2 class="menu-title">Home</h2></a>
      </li>
      

      <li class="sub-menu-parent">
        <a data-turbolinks='false' href="<%= read_alouds_chart_path %>" class="menu" id="home"><h2 class="menu-title">Read Aloud</h2></a>
      </li>

      <li class="sub-menu-parent">
        <a data-turbolinks='false' href="<%= pronunciation_index_path %>" class="menu" id="home"><h2 class="menu-title">Pronunciation</h2></a>
      </li>

      <li class="sub-menu-parent">
        <a data-turbolinks='false' href="<%= write_fr_dics_public_path %>" class="menu" id="home"><h2 class="menu-title">Write From Dictation</h2></a>
      </li>

      <li class="sub-menu-parent">
        <a data-turbolinks='false' href="<%= home_course_path %>" class="menu" id="home"><h2 class="menu-title">Schedule</h2></a>
      </li>   
      
    </ul> 

</nav>
<div style="height: 60px;">
</div>
<script>
  var pathName = window.location.pathname;
  if(pathName === "/")
    //$("#home").addClass("d-none");
    $("#home").attr('disabled', 'disabled')

  if(pathName !== "/read_alouds"){
    try {
      speechSynthesis.cancel(); 
    } catch (error) {
      console.log(error);
    }

    try {
      responsiveVoice.cancel();
    } catch (error) {
      console.log(error);
    }
  }


  $("#act-toggle-sidebar").click(function() {
    if ( $('#content-sidebar').is('.d-none') ) {
      $("#content-sidebar").removeClass("d-none");
    }
    else{
      $("#content-sidebar").addClass("d-none");
    }
  });

  $("#act-user-info").click(function(){
    if ( $('#content-user-info').is('.d-none') ) {
      $("#content-user-info").removeClass("d-none");
    }
    else{
      $("#content-user-info").addClass("d-none");
    }
  });
</script>

app/views/home/course.html.erb
<%= render 'header' %>
<div class="main-course">
  <div class="home-course row justify-content-center">
    <div class="col-lg-10">
      <div class="bg-white shadow p-2">
        <div class="student-grade-table p-4">
          <div class="row row-course-header d-flex">
            <div class="col-1 mt-3 mb-3 col-course-day font-weight-bold">DAY</div>
            <div class="col-4 mt-3 mb-3 col-course-skill font-weight-bold">SKILL</div>
            <div class="col-2 mt-3 mb-3 col-course-quality font-weight-bold">QUANTITY</div>
            <div class="col-2 mt-3 mb-3 col-course-status font-weight-bold">STATUS</div>
            <div class="col-3 mt-3 mb-3 col-course-action font-weight-bold">ACTIONS</div>
          </div>
          
          <% Course.where(user_id: 6).pluck(:day_id, :skill, :quality, :status, :id).sort.each do |course| %>
          <div class="row row-course panel-body d-flex border-top">
            <div class="col-1 mt-2 mb-2 col-course-day"><%= course.first %></div>
            <div class="col-4 mt-2 mb-2 col-course-skill"><%= course[1] %></div>
            <div class="col-2 mt-2 mb-2 col-course-quality"><%= course[2] %></div>
            <div class="col-2 mt-2 mb-2 col-course-status"><%= course[3] %></div>
            <div class="col-3 mt-2 mb-2 col-course-action">
              <a class="edit btn-sm btn-warning" style="display: unset;color: white;"><span class="fa fa-pencil"></span></a>
              <% if (course[1] == "Write From Dictation") %>
              <%= link_to '<span class="fa fa-tv"></span>'.html_safe, write_fr_dics_path(:audio => course[2], :status_id => course.last), :class => "test btn-sm btn-info", :style => "display: unset;color: white;", :"data-turbolinks" => false %>
              <%elsif (course[1] == "Read Aloud") %>
              <%= link_to '<span class="fa fa-tv"></span>'.html_safe, read_alouds_path(:audio => course[2], :status_id => course.last), :class => "test btn-sm btn-info", :style => "display: unset;color: white;", :"data-turbolinks" => false %>
              <% else %>
              <a class="test btn-sm btn-info" style="display: unset;color: white;" href="#"><span class="fa fa-tv"></span></a>
              <% end %>
              <% @course = Course.find(course.last) %>
              <%= link_to '<span class="fa fa-trash-o"></span>'.html_safe, @course, method: :delete, data: { confirm: 'Are you sure?' }, :class => "delete btn-sm btn-danger" %>
            </div>
          </div>
          <%= render 'edit_form_course', course: @course  %>
          
          <% end %>
          <%= render 'create_form_course' %>

        </div>
      </div>
    </div>
  </div>
<div>

<script>
  var $dataTable = $('.student-grade-table');
  $dataTable.on('click', '.edit', function(e) {
    var $row = $(this).closest('.row');
    $row.hide();
    $row.next().show();
  })
</script>

app/views/home/index.html.erb
<%= render 'header'%>
<%= render 'animation'%>