config/routes.rb
# coding: utf-8
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pronunciation/index'
  get 'pronunciation/only_word'
  get 'pronunciation/list_word'
  get 'pronunciation/store_alphabet_trainning'
  get 'admin/index'
  get 'admin/report'
  get 'build/index'
  resources :read_alouds, only: [:index, :chart, :report]
  get 'read_alouds/chart'
  get 'read_alouds/report'
  get 'course/create'
  post 'course/store'
  resources :course, only: [:edit, :update, :destroy]
  get 'home/course'
  resources :users, only: [:new, :create, :update]
  root "home#index"
  
  resources :sessions, only: [:new, :create, :destroy] 
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  resources :write_fr_dics, only: [:index, :public]
  resources :password_resets, only: [:edit, :update, :create, :new]

  get 'write_fr_dics/public'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Handle unavailable link
  get '*path' => redirect('/404_customize')

end

app/models/read_aloud.rb
class ReadAloud < ApplicationRecord
end

app/controllers/read_alouds_controller.rb
class ReadAloudsController < ApplicationController
  before_action :set_read_aloud, only: [:show, :edit, :update, :destroy]
  before_action :check_user
  
  # GET /read_alouds
  # GET /read_alouds.json
  def chart
    last_result = ReadAloudChart.where(user_id:current_user.id).order('updated_at DESC').first
    if last_result != nil && last_result.sentence.to_s == params[:sentence]
      return last_result.update(:rate => params[:rate], :result => params[:result])
    else
      unless params[:rate] == nil
        # check condition if :rate >= 55%, it will save :result
        if params[:rate].to_i >= 55
          result = ReadAloudChart.new(:user_id => current_user.id, :rate => params[:rate], :sentence => params[:sentence], :result => params[:result])
          result.save!
        else
          result = ReadAloudChart.new(:user_id => current_user.id, :rate => params[:rate], :sentence => params[:sentence])
          result.save!
        end
      end
    end
    
  end
  
  def index
    @read_alouds = params[:audio].to_i
    if params[:status_id]
      @status_id = params[:status_id]
      read_status = Course.all.find_by_id(params[:status_id])
      read_status.update(:status => "In Progress")
    end
  end
  
  # Report to admin 
  def report
    same_report = ReadAloudReport.where(user_id:current_user.id, updated_at: (Date.today).all_day, sentence: params[:sentence])
    if params[:rate].to_i >= 60
      
      if same_report != []
        same_report.update(:percent => params[:rate])
        render json: { status: 'update', message: "Your result updated successful." }
      else
        report = ReadAloudReport.new(:user_id => current_user.id,
                                     :sentence => params[:sentence],
                                     :percent => params[:rate],
                                     :result => params[:result])
        if report.save!
          render json: { status: 'success', message: "Saved" }
        else
          render json: { status: 'errors', message: "Occured errors!" }
        end
        
      end
      
    else
      render json: { status: 'error', message: "Your accuracy need larger than 60% " }
    end      
  end

  # GET /read_alouds/1
  # GET /read_alouds/1.json
  def show
  end

  # GET /read_alouds/new
  def new
    @read_aloud = ReadAloud.new
  end

  # GET /read_alouds/1/edit
  def edit
  end

  # POST /read_alouds
  # POST /read_alouds.json
  def create
    @read_aloud = ReadAloud.new(read_aloud_params)

    respond_to do |format|
      if @read_aloud.save
        format.html { redirect_to @read_aloud, notice: 'Read aloud was successfully created.' }
        format.json { render :show, status: :created, location: @read_aloud }
      else
        format.html { render :new }
        format.json { render json: @read_aloud.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /read_alouds/1
  # PATCH/PUT /read_alouds/1.json
  def update
    respond_to do |format|
      if @read_aloud.update(read_aloud_params)
        format.html { redirect_to @read_aloud, notice: 'Read aloud was successfully updated.' }
        format.json { render :show, status: :ok, location: @read_aloud }
      else
        format.html { render :edit }
        format.json { render json: @read_aloud.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /read_alouds/1
  # DELETE /read_alouds/1.json
  def destroy
    @read_aloud.destroy
    respond_to do |format|
      format.html { redirect_to read_alouds_url, notice: 'Read aloud was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_read_aloud
    @read_aloud = ReadAloud.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def read_aloud_params
    params.fetch(:read_aloud, {})
  end
end

app/helpers/read_alouds_helper.rb
module ReadAloudsHelper
  
  def get_chart_user()
    ReadAloudChart.where(user_id:current_user.id).order(:updated_at)
  end
  def list_days()
    data = get_chart_user()
    days = data.pluck(:updated_at).map{|x| Date.parse(x.to_s).to_s}.uniq
  end

  # def rate_by_day()
  def get_list_rate()
    data = get_chart_user()
    rates =  data.pluck(:rate)
    if rates.count < 30

      rates = rates + [0] * (30 - rates.count)
    else
      rates.last(30)
    end
  end

  def get_list_sentence()
    
    data = get_chart_user()
    
    sents =  data.pluck(:sentence).map{|x| "Sentence " + x.to_s}
    if sents.count < 30
      sents = sents + ["No data"] * (30 - sents.count)
    else
      sents.last(30)
    end
  end
  
end
# JSON.parse(list_days.replace(/&quot;/g,'"')),

app/views/read_alouds/_form.html.erb
<%= form_with(model: read_aloud, local: true) do |form| %>
  <% if read_aloud.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(read_aloud.errors.size, "error") %> prohibited this read_aloud from being saved:</h2>

      <ul>
      <% read_aloud.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/read_alouds/_notify.html.erb
<div class='notifications'>
  <div class='notification notice'  style='display: none;'>
    <div class='icon bg'></div>
    <!-- <a class='close delete-parent' href='#'></a> -->
    <div class='content'>
      <div class='message'>Your result updated successful.</div>
    </div>
  </div>
  <div class='notification success' style='display: none;'>
    <div class='icon bg'></div>
    <div class='content'>
      <div class='message'>Your result has shared.</div>
    </div>
  </div>
  <div class='notification warning' style='display: none;'>
    <div class='icon warning bg'></div>
    <!-- <a class='close delete-parent' href='#'></a> -->
    <div class='content'>
      <div class='message'>You need get the accuracy is larger than 60% to share result.</div>
    </div>
  </div>
  <div class='notification alert' style='display: none;'>
    <div class='icon alert bg' style="margin-top: -12px; margin-left: -1.2%"></div>
    <!-- <a class='close delete-parent' href='#'></a> -->
    <div class='content alert-color'>
      <div class='message'>Occured errors. Please try it again later.</div>
    </div>
  </div>
</div>

app/views/read_alouds/chart.html.erb
<%= render 'home/header' %>
<div class="main-read-aloud"> 
  <div class="read-alouds main-chart-read-aloud bg-white shadow p-2">
    <canvas id="allChart"></canvas>  
    <canvas id="todayChart" class="d-none"></canvas>
  </div>
</div>
<div class="action-bottom w-100 text-center mt-4">
  <%= link_to 'CONTINUE', read_alouds_path(:audio => ReadAloud.all.size), :class => "btn bg-blue-en4all text-light", :"data-turbolinks" => false %>
</div>


<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
  var allChart;
  var todayChart;
  function toggleCheckbox() {
    var checkChart = document.getElementById("toggle-chart").checked
    if(!checkChart) {
      $("#todayChart").addClass("d-none");
      $("#allChart").removeClass("d-none");
      todayChart.destroy();
      showAllChart();
    }
    else{
      $("#allChart").addClass("d-none");
      $("#todayChart").removeClass("d-none");
      allChart.destroy();
      showTodayChart();
    }
  }

  function showTodayChart() {
    var ctx = document.getElementById('todayChart').getContext('2d');
    var list_rate = '<%= get_list_rate() %>';
    var list_sent = '<%= get_list_sentence() %>';

    todayChart = new Chart(ctx, {
      // The type of chart we want to create
      type: 'bar',

      // The data for our dataset
      data: {
        // labels: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10',
        //          '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
        //         ],
        // labels: (JSON.parse(list_sent)).map(String),
        labels: JSON.parse(list_sent.replace(/&quot;/g,'"')),

        datasets: [
          // Jun
          {
            // data: [50, 55, 56, 58, 60, 55, 60, 55, 54, 58, 
            //        59, 53, 53, 55, 60, 65, 55, 54, 53, 52
            //       ],
            label: "Accuracy (%)",
            data: JSON.parse(list_rate),
            backgroundColor: [
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
              'rgba(95, 192, 84, 0.2)',
            ],
            borderColor: [
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
              'rgba(95, 192, 84, 1)',
            ],
            borderWidth: 1
          }
        ]
      },
      // Configuration options go here
      options: { 
        title: {
          display: true,
          text: 'RESULT OF YOUR RECORD'
        },
        scales: {
          yAxes: [{
            ticks: {
              min: 0,
              max: 100,
              stepSize: 10
            }
          }]
        }
      }
    })
  }

  function showAllChart() {
    var ctx = document.getElementById('allChart').getContext('2d');
    allChart = new Chart(ctx, {
      // The type of chart we want to create
      type: 'line',

      // The data for our dataset
      data: {
        labels: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10',
                 '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
                 '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
                 '31'],
        datasets: [
          // Jun
          {
            label: 'Jun',
            data: [50, 55, 56, 58, 60, 55, 60, 55, 54, 58, 
                   59, 53, 53, 55, 60, 65, 55, 54, 53, 52,
                   52, 55, 56, 54, 55, 58, 59, 59, 64, 59,
                   60],
            fill: false,
            borderColor: ['#ed5564']
          },
          // Feb
          {
            label: 'Feb',
            data: [60, 65, 66, 68, 60, 65, 60, 65, 64, 68, 
                   69, 63, 63, 65, 60, 65, 65, 64, 63, 56,
                   62, 65, 66, 64, 65, 68, 69, 69, 64, 69,
                   60],
            fill: false,
            borderColor: ['#ed5f55']
          },
          // Mar
          {
            label: 'Mar',
            data: [62, 67, 69, 68, 62, 67, 62, 67, 66, 68, 
                   69, 65, 65, 67, 62, 67, 67, 66, 65, 58,
                   64, 67, 68, 66, 67, 68, 69, 69, 66, 69,
                   62],
            fill: false,
            borderColor: ['#f57c4f']
          },
          // Apr
          {
            label: 'Apr',
            data: [70, 77, 79, 78, 72, 77, 72, 77, 76, 78, 
                   79, 75, 75, 77, 72, 77, 77, 76, 75, 78,
                   74, 77, 78, 76, 77, 78, 79, 79, 76, 79,
                   72],
            fill: false,
            borderColor: ['#fcce54']
          },
          // May
          {
            label: 'May',
            data: [75, 82, 84, 83, 77, 82, 77, 82, 81, 83, 
                   84, 80, 80, 82, 77, 82, 82, 81, 80, 83,
                   79, 82, 83, 81, 82, 83, 84, 84, 81, 84,
                   77],
            fill: false,
            borderColor: ['#99d468']
          },
          // Jun
          {
            label: 'Jun',
            data: [77, 82, 84, 83, 79, 82, 79, 82, 81, 83, 
                   84, 80, 80, 82, 79, 82, 82, 81, 80, 83,
                   79, 82, 83, 81, 82, 83, 84, 84, 81, 84,
                   79],
            fill: false,
            borderColor: ['#99d468']
          },
          // Jul
          {
            label: 'Jul',
            data: [87, 82, 84, 83, 89, 82, 89, 82, 81, 83, 
                   84, 80, 80, 82, 79, 82, 82, 81, 80, 83,
                   89, 82, 83, 81, 82, 83, 84, 84, 81, 84,
                   89],
            fill: false,
            borderColor: ['#41ca6e']
          },
          // Aug
          {
            label: 'Aug',
            data: [97, 92, 94, 93, 99, 92, 99, 92, 91, 93, 
                   94, 90, 90, 92, 99, 92, 92, 91, 90, 93,
                   99, 92, 93, 91, 92, 93, 94, 94, 91, 94,
                   99],
            fill: false,
            borderColor: ['#47cec0']
          },
          // Sep
          {
            label: 'Sep',
            data: [95, 87, 89, 88, 94, 87, 94, 87, 89, 88, 
                   89, 85, 85, 87, 94, 87, 87, 86, 85, 87,
                   94, 87, 88, 86, 87, 88, 89, 89, 86, 89,
                   95],
            fill: false,
            borderColor: ['#4ec2e7']
          },
          // Oct
          {
            label: 'Oct',
            data: [96, 97, 99, 98, 94, 97, 94, 97, 99, 98, 
                   99, 95, 95, 97, 94, 97, 97, 96, 95, 97,
                   94, 97, 98, 96, 97, 98, 99, 99, 96, 99,
                   95],
            fill: false,
            borderColor: ['#5c9ded']
          },
          // Nov
          {
            label: 'Nov',
            data: [100, 91, 93, 92, 98, 91, 98, 91, 93, 92, 
                   93, 89, 89, 91, 98, 91, 91, 90, 89, 91,
                   98, 91, 92, 90, 91, 92, 93, 93, 89, 93,
                   99],
            fill: false,
            borderColor: ['#9398ec']
          },
          // Dec
          {
            label: 'Dec',
            data: [99, 98, 98, 99, 97, 100, 100, 100, 100, 95, 
                   99, 99, 98, 100, 96, 99, 97, 98, 99, 99,
                   98, 100, 98, 98, 99, 100, 99, 99, 100, 97,
                   100],
            fill: false,
            borderColor: ['#cb93ee']
          }
        ]
      },

      // Configuration options go here
      options: { 
        title: {
          display: true,
          text: 'REULST FOR READ ALOUDS'
        },
        legend: {
          display: true,
          labels: {
            fontColor: 'rgb(255, 99, 132)'
          }
        }
      }
    });
  }

  $(document).ready(function() {
    // showAllChart();
    $("#allChart").addClass("d-none");
    $("#todayChart").removeClass("d-none");
    
    showTodayChart();
  });
</script>

app/views/read_alouds/edit.html.erb
<h1>Editing Read Aloud</h1>

<%= render 'form', read_aloud: @read_aloud %>

<%= link_to 'Show', @read_aloud %> |
<%= link_to 'Back', read_alouds_path %>

app/views/read_alouds/new.html.erb
<h1>New Read Aloud</h1>

<%= render 'form', read_aloud: @read_aloud %>

<%= link_to 'Back', read_alouds_path %>

app/views/read_alouds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_read_aloud_path(@read_aloud) %> |
<%= link_to 'Back', read_alouds_path %>

<%= render 'home/header' %>

<div class="read-alouds container bg-white shadow p-2">
  <div class="can-toggle">
    <input id="toggle-chart" type="checkbox" onchange="toggleCheckbox()">
    <label for="toggle-chart">
      <div class="can-toggle__switch" data-checked="Today" data-unchecked="All"></div>
      <div class="can-toggle__label-text"></div>
    </label>
  </div>

  <canvas id="allChart"></canvas>
  
  <canvas id="todayChart" class="d-none"></canvas>

  <div class="w-100 text-center mt-4"><button class="btn bg-blue-en4all text-light">CONTINUTE</button></div>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
  var allChart;
  var todayChart;
  function toggleCheckbox() {
    var checkChart = document.getElementById("toggle-chart").checked
    if(!checkChart) {
      $("#todayChart").addClass("d-none");
      $("#allChart").removeClass("d-none");
      todayChart.destroy();
      showAllChart();
    }
    else{
      $("#allChart").addClass("d-none");
      $("#todayChart").removeClass("d-none");
      allChart.destroy();
      showTodayChart();
    }
  }

  function showTodayChart() {
    var ctx = document.getElementById('todayChart').getContext('2d');
    todayChart = new Chart(ctx, {
      // The type of chart we want to create
        type: 'bar',

        // The data for our dataset
        data: {
          labels: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10',
                    '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
                  ],
            datasets: [
              // Jun
              {
                data: [50, 55, 56, 58, 60, 55, 60, 55, 54, 58, 
                      59, 53, 53, 55, 60, 65, 55, 54, 53, 52
                      ],
                backgroundColor: [
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                  'rgba(95, 192, 84, 0.2)',
                ],
                borderColor: [
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                  'rgba(95, 192, 84, 1)',
                ],
                borderWidth: 1
              }
            ]
        },
        // Configuration options go here
        options: { 
          title: {
                display: true,
                text: 'TODAY'
            },
        }
    })
  }

  function showAllChart() {
    var ctx = document.getElementById('allChart').getContext('2d');
    allChart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'line',

        // The data for our dataset
        data: {
            labels: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10',
                    '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
                    '21', '22', '23', '24', '25', '26', '27', '28', '29', '30',
                    '31'],
            datasets: [
              // Jun
              {
                label: 'Jun',
                data: [50, 55, 56, 58, 60, 55, 60, 55, 54, 58, 
                      59, 53, 53, 55, 60, 65, 55, 54, 53, 52,
                      52, 55, 56, 54, 55, 58, 59, 59, 64, 59,
                      60],
                fill: false,
                borderColor: ['#ed5564']
              },
              // Feb
              {
                label: 'Feb',
                data: [60, 65, 66, 68, 60, 65, 60, 65, 64, 68, 
                      69, 63, 63, 65, 60, 65, 65, 64, 63, 56,
                      62, 65, 66, 64, 65, 68, 69, 69, 64, 69,
                      60],
                fill: false,
                borderColor: ['#ed5f55']
              },
              // Mar
              {
                label: 'Mar',
                data: [62, 67, 69, 68, 62, 67, 62, 67, 66, 68, 
                      69, 65, 65, 67, 62, 67, 67, 66, 65, 58,
                      64, 67, 68, 66, 67, 68, 69, 69, 66, 69,
                      62],
                fill: false,
                borderColor: ['#f57c4f']
              },
              // Apr
              {
                label: 'Apr',
                data: [70, 77, 79, 78, 72, 77, 72, 77, 76, 78, 
                      79, 75, 75, 77, 72, 77, 77, 76, 75, 78,
                      74, 77, 78, 76, 77, 78, 79, 79, 76, 79,
                      72],
                fill: false,
                borderColor: ['#fcce54']
              },
              // May
              {
                label: 'May',
                data: [75, 82, 84, 83, 77, 82, 77, 82, 81, 83, 
                      84, 80, 80, 82, 77, 82, 82, 81, 80, 83,
                      79, 82, 83, 81, 82, 83, 84, 84, 81, 84,
                      77],
                fill: false,
                borderColor: ['#99d468']
              },
              // Jun
              {
                label: 'Jun',
                data: [77, 82, 84, 83, 79, 82, 79, 82, 81, 83, 
                      84, 80, 80, 82, 79, 82, 82, 81, 80, 83,
                      79, 82, 83, 81, 82, 83, 84, 84, 81, 84,
                      79],
                fill: false,
                borderColor: ['#99d468']
              },
              // Jul
              {
                label: 'Jul',
                data: [87, 82, 84, 83, 89, 82, 89, 82, 81, 83, 
                      84, 80, 80, 82, 79, 82, 82, 81, 80, 83,
                      89, 82, 83, 81, 82, 83, 84, 84, 81, 84,
                      89],
                fill: false,
                borderColor: ['#41ca6e']
              },
              // Aug
              {
                label: 'Aug',
                data: [97, 92, 94, 93, 99, 92, 99, 92, 91, 93, 
                      94, 90, 90, 92, 99, 92, 92, 91, 90, 93,
                      99, 92, 93, 91, 92, 93, 94, 94, 91, 94,
                      99],
                fill: false,
                borderColor: ['#47cec0']
              },
              // Sep
              {
                label: 'Sep',
                data: [95, 87, 89, 88, 94, 87, 94, 87, 89, 88, 
                      89, 85, 85, 87, 94, 87, 87, 86, 85, 87,
                      94, 87, 88, 86, 87, 88, 89, 89, 86, 89,
                      95],
                fill: false,
                borderColor: ['#4ec2e7']
              },
              // Oct
              {
                label: 'Oct',
                data: [96, 97, 99, 98, 94, 97, 94, 97, 99, 98, 
                      99, 95, 95, 97, 94, 97, 97, 96, 95, 97,
                      94, 97, 98, 96, 97, 98, 99, 99, 96, 99,
                      95],
                fill: false,
                borderColor: ['#5c9ded']
              },
              // Nov
              {
                label: 'Nov',
                data: [100, 91, 93, 92, 98, 91, 98, 91, 93, 92, 
                      93, 89, 89, 91, 98, 91, 91, 90, 89, 91,
                      98, 91, 92, 90, 91, 92, 93, 93, 89, 93,
                      99],
                fill: false,
                borderColor: ['#9398ec']
              },
              // Dec
              {
                label: 'Dec',
                data: [99, 98, 98, 99, 97, 100, 100, 100, 100, 95, 
                      99, 99, 98, 100, 96, 99, 97, 98, 99, 99,
                      98, 100, 98, 98, 99, 100, 99, 99, 100, 97,
                      100],
                fill: false,
                borderColor: ['#cb93ee']
              }
            ]
        },

        // Configuration options go here
        options: { 
          title: {
                display: true,
                text: 'REULST FOR READ ALOUDS'
            },
            legend: {
                display: true,
                labels: {
                    fontColor: 'rgb(255, 99, 132)'
                }
            }
        }
    });
  }

$(document).ready(function() {
  showAllChart();  
});
</script>